# LSTM - Stock Analysis

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import io


In [0]:
# https://github.com/mwitiderrick/stockprice
# https://www.kdnuggets.com/2018/11/keras-long-short-term-memory-lstm-model-predict-stock-prices.html

In [14]:
from google.colab import files
uploaded = files.upload()
print(uploaded)

Saving GENTING_data_set.csv to GENTING_data_set (1).csv
Saving GENTING_train_set.csv to GENTING_train_set (3).csv
Saving GENTING_test_set.csv to GENTING_test_set (1).csv
{'GENTING_data_set.csv': b'"Date","Price","Open","High","Low","Vol.","Change %"\n"Jan 18, 2019","6.79","6.83","6.89","6.75","10.25M","-0.44%"\n"Jan 17, 2019","6.82","6.47","6.84","6.47","12.36M","6.23%"\n"Jan 16, 2019","6.42","6.48","6.50","6.38","6.92M","-0.47%"\n"Jan 15, 2019","6.45","6.39","6.48","6.38","4.39M","1.10%"\n"Jan 14, 2019","6.38","6.45","6.49","6.31","3.68M","-1.09%"\n"Jan 11, 2019","6.45","6.43","6.45","6.36","2.73M","0.78%"\n"Jan 10, 2019","6.40","6.47","6.48","6.25","4.06M","-0.16%"\n"Jan 09, 2019","6.41","6.34","6.44","6.25","5.76M","1.58%"\n"Jan 08, 2019","6.31","6.09","6.34","6.07","5.10M","4.13%"\n"Jan 07, 2019","6.06","5.95","6.08","5.95","4.65M","2.19%"\n"Jan 04, 2019","5.93","5.96","5.97","5.91","8.62M","-0.50%"\n"Jan 03, 2019","5.96","6.00","6.06","5.95","3.51M","-0.67%"\n"Jan 02, 2019","6.00"

In [0]:
UOM = {'K': 1000, 'M': 1000000}

def convert_to_numeric(val):
    return float(val[:-1]) * UOM[val[-1]]

def clean_dataset(df):
    df.rename(columns={'Price':'Close', 'Vol.':'Volume'}, inplace=True)
    df.drop(columns=['Change %'], axis=1, inplace=True)
    df['Date'] = pd.to_datetime(df['Date'])
    df['Volume'] = df['Volume'].apply(convert_to_numeric)
    #df.sort_values(by=['Date'], ascending=True, inplace=True)
    #df.set_index('Date', inplace=True)

# dataset = pd.read_csv('data/GENTING_train_set.csv', parse_dates=True)
#print(uploaded)
dataset = pd.read_csv(io.StringIO(uploaded['GENTING_train_set.csv'].decode('utf-8')), parse_dates=True)
clean_dataset(dataset)
training_set = dataset.iloc[:, 1:2].values

In [35]:
# Feature Scaling
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
print(training_set_scaled)

[[0.15948276]
 [0.125     ]
 [0.14008621]
 ...
 [0.74137931]
 [0.75431034]
 [0.76293103]]


In [37]:
X_train = []
y_train = []
print(len(training_set_scaled))
for i in range(60, len(training_set_scaled)):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(training_set_scaled)
print(X_train)
print(y_train)

1768
[[0.15948276]
 [0.125     ]
 [0.14008621]
 ...
 [0.74137931]
 [0.75431034]
 [0.76293103]]
[[[0.15948276]
  [0.125     ]
  [0.14008621]
  ...
  [0.45043103]
  [0.45258621]
  [0.45474138]]

 [[0.125     ]
  [0.14008621]
  [0.12715517]
  ...
  [0.45258621]
  [0.45474138]
  [0.45474138]]

 [[0.14008621]
  [0.12715517]
  [0.13362069]
  ...
  [0.45474138]
  [0.45474138]
  [0.46336207]]

 ...

 [[0.87931034]
  [0.92241379]
  [0.90517241]
  ...
  [0.62715517]
  [0.66810345]
  [0.72844828]]

 [[0.92241379]
  [0.90517241]
  [0.88362069]
  ...
  [0.66810345]
  [0.72844828]
  [0.74137931]]

 [[0.90517241]
  [0.88362069]
  [0.85775862]
  ...
  [0.72844828]
  [0.74137931]
  [0.75431034]]]
[0.45474138 0.46336207 0.45474138 ... 0.74137931 0.75431034 0.76293103]
