In [10]:
import torch

In [11]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [12]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [15]:
z = y * y * 3
out = z.mean()  # Average and get a scalar
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [18]:
a = torch.randn(2,2)
print(a)

tensor([[-1.0620,  0.1010],
        [ 0.2381,  1.7854]])


In [20]:
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [21]:
a.requires_grad_(True)

tensor([[ 1.5451, -0.3369],
        [-0.9373,  6.8199]], requires_grad=True)

In [23]:
b = (a * a).sum()
print(b)

tensor(49.8910, grad_fn=<SumBackward0>)


In [24]:
print(b.grad_fn)

## Gradients

In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [28]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(x, y)

tensor([-0.5963, -0.6667,  0.1919], requires_grad=True) tensor([-1.1926, -1.3335,  0.3838], grad_fn=<MulBackward0>)


In [33]:
while y.data.norm() < 1000:  # torch.sqrt(torch.sum(torch.pow(y, 2)))
    y = y * 2
    
print(y)

tensor([-1221.2360, -1365.4885,   393.0008], grad_fn=<MulBackward0>)


SyntaxError: invalid syntax (<ipython-input-34-5bbf901aa924>, line 1)