In [91]:
# https://towardsdatascience.com/pytorch-autograd-understanding-the-heart-of-pytorchs-magic-2686cd94ec95
# https://towardsdatascience.com/getting-started-with-pytorch-part-1-understanding-how-automatic-differentiation-works-5008282073ec

import torch

In [59]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [60]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [61]:
z = y * y * 3
out = z.mean()  # Average and get a scalar
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [62]:
a = torch.randn(2,2)
print(a)

tensor([[ 1.0023,  0.5201],
        [-1.2143, -0.4842]])


In [63]:
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [64]:
a.requires_grad_(True)

tensor([[ 1.3139e+03, -3.2516e+00],
        [ 1.6452e+00,  9.7865e-01]], requires_grad=True)

In [65]:
b = (a * a).sum()
print(b)

tensor(1726233.5000, grad_fn=<SumBackward0>)


In [66]:
print(b.grad_fn)

## Gradients

In [67]:
out.backward()

In [68]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [72]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(x, y)

tensor([ 0.0563, -1.2110,  0.4497], requires_grad=True) tensor([ 0.1127, -2.4220,  0.8993], grad_fn=<MulBackward0>)


In [73]:
while y.data.norm() < 1000:  # torch.sqrt(torch.sum(torch.pow(y, 2)))
    print(y)
    y = y * 2
    
print(y)

tensor([ 0.1127, -2.4220,  0.8993], grad_fn=<MulBackward0>)
tensor([ 0.2253, -4.8440,  1.7986], grad_fn=<MulBackward0>)
tensor([ 0.4506, -9.6881,  3.5973], grad_fn=<MulBackward0>)
tensor([  0.9012, -19.3761,   7.1946], grad_fn=<MulBackward0>)
tensor([  1.8024, -38.7522,  14.3892], grad_fn=<MulBackward0>)
tensor([  3.6049, -77.5045,  28.7783], grad_fn=<MulBackward0>)
tensor([   7.2098, -155.0089,   57.5567], grad_fn=<MulBackward0>)
tensor([  14.4195, -310.0178,  115.1134], grad_fn=<MulBackward0>)
tensor([  28.8391, -620.0356,  230.2267], grad_fn=<MulBackward0>)
tensor([   57.6781, -1240.0713,   460.4535], grad_fn=<MulBackward0>)


In [74]:
v = torch.tensor([1.0, 1.0, 1.0], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1024., 1024., 1024.])


## Jacobian Matrix

In [89]:
x = torch.ones(2,2, requires_grad=True)
y = x + 2
z = y * y * 3
print(x)
print(y)
print(z)
a = torch.tensor([[0.5,1.0],[1.0,1.0]])
z.backward(a)
print(x.grad)

#out = z.mean()  # Average and get a scalar
#out.backward()
#print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[ 9., 18.],
        [18., 18.]])


## No Grad

In [90]:
print(x.requires_grad)
print( (x ** 2).requires_grad)
with torch.no_grad():
    print( (x**2).requires_grad)

True
True
False
