In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0842e-19, 8.4297e-13]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3850, 0.8262, 0.0938],
        [0.8238, 0.5517, 0.1528],
        [0.3521, 0.5634, 0.4141],
        [0.7686, 0.6100, 0.6276],
        [0.9297, 0.8774, 0.6611]])


In [6]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x  = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.5792, -0.3063,  0.1403],
        [ 0.0065, -0.0280,  0.3095],
        [-1.3003, -0.5563,  1.1800],
        [-0.9401,  0.3611, -0.5768],
        [ 0.2337, -0.7614, -0.6925]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print(y)

tensor([[0.9323, 0.8069, 0.6573],
        [0.2693, 0.6963, 0.1914],
        [0.8114, 0.3784, 0.8921],
        [0.5907, 0.8552, 0.0621],
        [0.5884, 0.9282, 0.3266]])


In [15]:
print(x+y)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [16]:
print(torch.add(x,y))

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [18]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [20]:
y.add_(x)
print(y)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [21]:
print(x[:, 1])

tensor([-0.3063, -0.0280, -0.5563,  0.3611, -0.7614])
