In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0842e-19, 8.4297e-13]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3850, 0.8262, 0.0938],
        [0.8238, 0.5517, 0.1528],
        [0.3521, 0.5634, 0.4141],
        [0.7686, 0.6100, 0.6276],
        [0.9297, 0.8774, 0.6611]])


In [6]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x  = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.5792, -0.3063,  0.1403],
        [ 0.0065, -0.0280,  0.3095],
        [-1.3003, -0.5563,  1.1800],
        [-0.9401,  0.3611, -0.5768],
        [ 0.2337, -0.7614, -0.6925]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print(y)

tensor([[0.9323, 0.8069, 0.6573],
        [0.2693, 0.6963, 0.1914],
        [0.8114, 0.3784, 0.8921],
        [0.5907, 0.8552, 0.0621],
        [0.5884, 0.9282, 0.3266]])


In [15]:
print(x+y)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [16]:
print(torch.add(x,y))

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [18]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [20]:
y.add_(x)
print(y)

tensor([[ 0.3531,  0.5007,  0.7976],
        [ 0.2758,  0.6683,  0.5009],
        [-0.4889, -0.1779,  2.0721],
        [-0.3494,  1.2163, -0.5147],
        [ 0.8220,  0.1668, -0.3660]])


In [21]:
print(x[:, 1])

tensor([-0.3063, -0.0280, -0.5563,  0.3611, -0.7614])


In [26]:
x = torch.randn(4,4)
y = x.view(16)
print(x)
print(y)

tensor([[ 1.4281,  1.1120,  0.1057, -0.2549],
        [-0.7686, -0.9752,  0.6331,  0.2570],
        [-0.5869,  1.5443, -2.0243,  0.6657],
        [-2.1835,  1.5771,  0.5116,  1.2650]])
tensor([ 1.4281,  1.1120,  0.1057, -0.2549, -0.7686, -0.9752,  0.6331,  0.2570,
        -0.5869,  1.5443, -2.0243,  0.6657, -2.1835,  1.5771,  0.5116,  1.2650])


In [27]:
z = x.view(-1,8)
print(z)

tensor([[ 1.4281,  1.1120,  0.1057, -0.2549, -0.7686, -0.9752,  0.6331,  0.2570],
        [-0.5869,  1.5443, -2.0243,  0.6657, -2.1835,  1.5771,  0.5116,  1.2650]])


In [28]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1846])
0.184559628367424


In [33]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [34]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [37]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [39]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [40]:
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [41]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [44]:
torch.ones_like?

Docstring:
ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `1`, with the same size as
:attr:`input`. ``torch.ones_like(input)`` is equivalent to
``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

.. warning::
    As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
    the old ``torch.ones_like(input, out=output)`` is equivalent to
    ``torch.ones(input.size(), out=output)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    device (:class:`torch.device`, optional): the desire

In [43]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
